from typing import Any, Dict, List

class Pipeline:
    def __call__(self, inputs: str, *args: Any, **kwargs: Any) -> List[Dict[str, Any]]: ...
    def __getitem__(self, idx: int) -> Dict[str, Any]: ...

def pipeline(task: str, model: str | None = None, *args: Any, **kwargs: Any) -> Pipeline: ...
