name: Auto Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - run: |
        python -m pip install --upgrade pip
        pip install build flake8
        flake8 codemood --max-line-length=88 --ignore=E203,W503

  auto-publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Auto-bump version
      run: |
        python -c "
        import re
        with open('pyproject.toml', 'r') as f: content = f.read()
        match = re.search(r'version = \"(\d+)\.(\d+)\.(\d+)\"', content)
        major, minor, patch = map(int, match.groups())
        patch += 1
        new_version = f'{major}.{minor}.{patch}'
        new_content = re.sub(r'version = \"\d+\.\d+\.\d+\"', f'version = \"{new_version}\"', content)
        with open('pyproject.toml', 'w') as f: f.write(new_content)
        print(f'Bumped to {new_version}')
        "
    - name: Build and publish
      run: |
        python -m pip install --upgrade pip build
        python -m build
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip-existing: true
